POST http://localhost:3003/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhemltb24iLCJpZCI6IjVlYTliYTM1MTU1YWU5MjUzYjlmNzY2ZiIsImlhdCI6MTU4ODIxMjAyOX0.uO2RV3lfXx6Y8VQAO3AxuJy6Yy9pG9o3hqNADzzSL1s

{
    "title": "why wont you work",
    "author": "Raziel",
    "url": "http://damn.com/",
    "likes": 1238
}